services:
  - type: web
    name: physician-notetaker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0